[package]
name = "dhcp"
version = "2022.0.0"
edition = "2021"

[dependencies]
async-std = {version = "^1.11.0", features = ["attributes", "tokio1"]}
env_logger = "0.8.2"
hyper = "^0.14.18"
hyperlocal = "^0.8.0"
log = "^0.4.17"
tokio = { version = "1", features = ["full"] }
